#ifdef VENDOR_EDIT
#obj-$(CONFIG_OPPO_COMMON_SOFT)  +=  oppo_project/


#obj-$(CONFIG_OPPO_HYPNUS)       +=  oppo_hypnus/

#obj-$(CONFIG_OPPO_SHUTDOWN_DETECT)  +=  oppo_shutdown_detect/
#endif /* VENDOR_EDIT */
#ifdef VENDOR_EDIT
#obj-$(CONFIG_OPPO_CRITICALLOG)  +=  oppo_criticallog/
obj-y  +=  oppo_criticallog/

#obj-$(CONFIG_OPPO_PHOENIX)     +=  oppo_phoenix/
#endif /* VENDOR_EDIT */

#ifdef VENDOR_EDIT
#obj-$(CONFIG_OPPO_KEY_HANDLE)    +=  oppo_key_handle/
#endif /* VENDOR_EDIT */

